### ISSUE TITLE
[Refactoring]: SpotlessApply on commit

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#5187]
### Describe the problem

I have spent many frustrating hours trying to commit code that has been rejected by the code formatting requirement.
Apart from simply forgetting to run ./gradlew spotlessApply, this is at its worst when my IDE reformats the code automatically between running spotless and me committing the code.
I spent the best part of a day trying to commit code that I eventually worked out differed only in the order of the import statements.

### The improvement you'd like to see

change [verify-build.yml](https://github.com/RPTools/maptool/blob/develop/.github/workflows/verify-build.yml) from
```
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: "21"
      - name: spotlessCheck
        run: ./gradlew spotlessCheck
```
To
```
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: "21"
      - name: spotlessApply
        run: ./gradlew spotlessApply
     - name: spotlessCheck
        run: ./gradlew spotlessCheck
```
or whatever is required so that it only fails on grievous errors like missing braces.

### Expected Benefits

Committed code will always be formatted correctly. People can format however they like prior to committing their code and the main codebase retains its formatted intergity.

### Additional Context

Many people will be a lot happier over time. More time can be spent coding instead of overcoming instrigent scripts fighting each other.
